<?xml version="1.0"?>
<robot name="sainsmart" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="main_base_width" value="0.05" />
  <xacro:property name="main_base_bodylen" value="0.06" />
  <xacro:property name="main_base_dims" value="0.1" />
  <xacro:property name="main_base_height" value="0.01" />
  <xacro:property name="pi" value="3.1415" />
  <xacro:property name="arm_support_height" value="0.07" />
  <xacro:property name="arm_support_width" value="0.07" />

  <xacro:property name="base_arm_len" value="0.2" />
  <xacro:property name="base_arm_width" value="0.02" />

  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
  </xacro:macro>



  <link name="elbow">
    <visual>
      <geometry>
        <box size="0.05 0.05 ${arm_support_height}"/>
      </geometry>
      <material name="blue"/>
      <origin xyz="0 0 0"/>

    </visual>
    <collision>
      <geometry>
        <box size="${main_base_dims} ${main_base_dims} ${main_base_dims}"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="10"/>
  </link>

  <joint name="eblow" type="continuous">
    <axis xyz="1 0 0" rpy="0 0 0" />

    <parent link="base_arm"/>
    <child link="elbow"/>
    <origin xyz="0 0 ${ base_arm_len }"/>
  </joint>


  <link name="base_arm">
    <visual>
      <geometry>
        <cylinder radius="${base_arm_width}" length="${base_arm_len}"/>
      </geometry>
      <material name="blue"/>
      <origin xyz="${base_arm_width} 0 ${ base_arm_len/2}"/>

    </visual>
    <collision>
      <geometry>
        <cylinder radius="${main_base_width}" length="${main_base_bodylen}"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="10"/>
  </link>

  <joint name="shoulder" type="continuous">
    <axis xyz="1 0 0" rpy="0 0 0" />

    <parent link="base_arm_support"/>
    <child link="base_arm"/>
    <origin xyz="0 0 ${(main_base_bodylen + main_base_height )}"/>
  </joint>

  <link name="base_arm_support">
    <visual>
      <geometry>
        <box size="0.01 0.1 ${arm_support_height}"/>
      </geometry>
      <material name="blue"/>
      <origin xyz="0 0 ${(main_base_bodylen ) + main_base_height }"/>

    </visual>
    <collision>
      <geometry>
        <box size="${main_base_dims} ${main_base_dims} ${main_base_dims}"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="10"/>
  </link>

  <joint name="base_arm_support_to_main_base" type="fixed">
    <axis xyz="0 0 1" rpy="0 0 0" />

    <parent link="main_base"/>
    <child link="base_arm_support"/>
    <origin xyz="0 0 0"/>
  </joint>

  <link name="main_base">
    <visual>
      <geometry>
        <cylinder radius="${main_base_width}" length="${main_base_bodylen}"/>
      </geometry>
      <material name="blue"/>
      <origin xyz="0 0 ${(main_base_bodylen/2.0) + (main_base_height/2.0) }"/>

    </visual>
    <collision>
      <geometry>
        <cylinder radius="${main_base_width}" length="${main_base_bodylen}"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="10"/>
  </link>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${main_base_dims} ${main_base_dims} ${main_base_height}"/>
      </geometry>
      <material name="blue"/>
      <origin xyz="0 0 0"/>

    </visual>
    <collision>
      <geometry>
        <box size="${main_base_dims} ${main_base_dims} ${main_base_dims}"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="10"/>
  </link>

  <joint name="base" type="continuous">
    <axis xyz="0 0 1" rpy="0 0 0" />

    <parent link="base_link"/>
    <child link="main_base"/>
    <origin xyz="0 0 0"/>
  </joint>

</robot>