<?xml version="1.0"?>
<robot name="sainsmart" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="main_base_width" value="0.05" />
  <xacro:property name="main_base_bodylen" value="0.06" />
  <xacro:property name="main_base_dims" value="0.1" />
  <xacro:property name="main_base_height" value="0.01" />
  <xacro:property name="supportlen" value="0.07" />
  <xacro:property name="pi" value="3.1415" />


  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
  </xacro:macro>




<!-- 
  <xacro:macro name="support" params="prefix reflect">
    <link name="${prefix}_support">
      <visual>
        <geometry>
          <box size="${supportlen} 0.1 0.2"/>
        </geometry>
        <origin xyz="0 0 -${supportlen/2}" rpy="0 ${pi/2} 0"/>
        <material name="white"/>
      </visual>
      <collision>
        <geometry>
          <box size="${supportlen} 0.1 0.2"/>
        </geometry>
        <origin xyz="0 0 -${supportlen/2}" rpy="0 ${pi/2} 0"/>
      </collision>
      <xacro:default_inertial mass="10"/>
    </link>

    <joint name="base_to_${prefix}_support" type="fixed">
      <parent link="main_base"/>
      <child link="${prefix}_support"/>
      <origin xyz="0 ${reflect*(main_base_width+.02)} 0.25" />
    </joint>

    <link name="${prefix}_base">
      <visual>
        <geometry>
          <box size="${main_base_dims} 0.1 0.1"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <geometry>
          <box size="${main_base_dims} 0.1 0.1"/>
        </geometry>
      </collision>
      <xacro:default_inertial mass="10"/>
    </link>

    <joint name="${prefix}_base_joint" type="fixed">
      <parent link="${prefix}_support"/>
      <child link="${prefix}_base"/>
      <origin xyz="0 0 ${-supportlen}" />
    </joint>
  </xacro:macro>

  <xacro:support prefix="right" reflect="-1" />
  <xacro:support prefix="left" reflect="1" /> -->

  <link name="main_base">
    <visual>
      <geometry>
        <cylinder radius="${main_base_width}" length="${main_base_bodylen}"/>
      </geometry>
      <material name="blue"/>
      <origin xyz="0 0 ${(main_base_bodylen/2.0) + main_base_height }"/>

    </visual>
    <collision>
      <geometry>
        <cylinder radius="${main_base_width}" length="${main_base_bodylen}"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="10"/>
  </link>


  <link name="base_link">
    <visual>
      <geometry>
        <box size="${main_base_dims} ${main_base_dims} ${main_base_height}"/>
      </geometry>
      <material name="blue"/>
      <origin xyz="0 0 0"/>

    </visual>
    <collision>
      <geometry>
        <box size="${main_base_dims} ${main_base_dims} ${main_base_dims}"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="10"/>
  </link>

  <joint name="base_link_to_main_base" type="continuous">
    <axis xyz="0 0 1" rpy="0 0 0" />

    <parent link="base_link"/>
    <child link="main_base"/>
    <origin xyz="0 0 0"/>
  </joint>

</robot>